
services:

  #----------------------------------------------------------------------------#
  #                                    NGINX                                   #
  #----------------------------------------------------------------------------#
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: services/nginx/
    ports:
      - 443:443
    networks:
      - trancendence
    volumes:
      - certificate:/var/ssl_cert/
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      server:
        condition: service_started
        restart: true
    restart: "always"

  #----------------------------------------------------------------------------#
  #                                    CERTIFICATE                             #
  #----------------------------------------------------------------------------#
  certificate:
    container_name: certificate
    image: certificate
    build:
      context: services/certificate/
    volumes:
      - certificate:/var/ssl_cert/
    networks:
      - trancendence
    restart: "no"

  #----------------------------------------------------------------------------#
  #                                    SERVER                                  #
  #----------------------------------------------------------------------------#
  server:
    container_name: server
    image: server
    build:
      context: src/server/
    networks:
      - trancendence
    volumes:
      - www:/var/www
      - server-srcs:/var/src/server/srcs
      - server-node_modules:/var/src/server/node_modules
    # healthcheck:
    #   test: ["CMD", "curl", "http://server:3000/"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 10
    restart: "always"

  #----------------------------------------------------------------------------#
  #                                    CLIENT                                  #
  #----------------------------------------------------------------------------#
  client:
    container_name: client
    image: client 
    build:
      context: services/client/
    volumes:
      - client:/var/src/client
      - www:/var/www
    restart: "always"

volumes:
  certificate:
    name: certificate
    driver: local
    driver_opts:
      device: ./data/certificate
      o: bind
      type: none
  client:
    name: client
    driver: local
    driver_opts:
      device: ./src/client
      o: bind
      type: none
  www:
    name: www
    driver: local
    driver_opts:
      device: ./data/www
      o: bind
      type: none
  server-node_modules:
    name: server-node_modules
    driver: local
    driver_opts:
      device: ./src/server/node_modules
      o: bind
      type: none
  server-srcs:
    name: server-srcs
    driver: local
    driver_opts:
      device: ./src/server/srcs/
      o: bind
      type: none


networks:
  trancendence:
    name: trancendence
    driver: bridge
