
services:

  #----------------------------------------------------------------------------#
  #                                    NGINX                                   #
  #----------------------------------------------------------------------------#
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: services/nginx/
    ports:
      - 80:80
      - 443:443
    networks:
      - trancendence
    volumes:
      - html:/var/www/html
      - certificate:/var/ssl_cert/
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 10

  #----------------------------------------------------------------------------#
  #                                    CERTIFICATE                             #
  #----------------------------------------------------------------------------#
  certificate:
    container_name: certificate
    image: certificate
    build:
      context: services/certificate/
    volumes:
      - certificate:/var/ssl_cert/
    networks:
      - trancendence
    restart: "no"


volumes:
  html:
    name: html
    driver: local
    driver_opts:
      device: ./data/html
      o: bind
      type: none
  certificate:
    name: certificate
    driver: local
    driver_opts:
      device: ./data/certificate
      o: bind
      type: none

networks:
  trancendence:
    name: trancendence
    driver: bridge
