
services:

  #----------------------------------------------------------------------------#
  #                                    NGINX                                   #
  #----------------------------------------------------------------------------#
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: services/nginx/
    ports:
      - 80:80
      - 443:443
    networks:
      - trancendence
    volumes:
      - html:/var/www/html
      - certificate:/var/ssl_cert/
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 10
    depends_on:
      server:
        condition: service_healthy
        restart: true
    restart: "always"

  #----------------------------------------------------------------------------#
  #                                    CERTIFICATE                             #
  #----------------------------------------------------------------------------#
  certificate:
    container_name: certificate
    image: certificate
    build:
      context: services/certificate/
    volumes:
      - certificate:/var/ssl_cert/
    networks:
      - trancendence
    restart: "no"

  #----------------------------------------------------------------------------#
  #                                    SERVER                                  #
  #----------------------------------------------------------------------------#
  server:
    container_name: server
    image: server
    build:
      context: services/server/
    networks:
      - trancendence
    volumes:
      - srcs:/var/
    healthcheck:
      test: ["CMD", "curl", "http://server:3000/"]
      interval: 5s
      timeout: 5s
      retries: 10


volumes:
  html:
    name: html
    driver: local
    driver_opts:
      device: ./data/html
      o: bind
      type: none
  certificate:
    name: certificate
    driver: local
    driver_opts:
      device: ./data/certificate
      o: bind
      type: none
  srcs:
    name: src
    driver: local
    driver_opts:
      device: ./src/
      o: bind
      type: none

networks:
  trancendence:
    name: trancendence
    driver: bridge
